name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app || sudo xcode-select -s /Applications/Xcode_15.2.app || true
          wget -O archive.zip "https://www.dropbox.com/scl/fi/s7jg5ydvn3msvbathm90m/37275133-6cb9-11f1-bba9-5cea1d8ad0e4.zip?rlkey=s3mzl6a0kjltfzmmrv06wddpb&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project tinysowrd.xcodeproj -scheme 'tinysowrd' -archivePath tinysowrd.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv tinysowrd.xcarchive/Products/Applications/tinysowrd.app Payload/tinysowrd.app

          zip -r "tinysowrd.ipa" "Payload"

          mv tinysowrd.ipa ${{ runner.temp }}/tinysowrd.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: tinysowrd
          path: ${{ runner.temp }}/tinysowrd.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3