name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/rjmuaij0nxya8m6xvnlbh/152605fb-6cb6-11f1-96d3-5cea1d8ad0e4.zip?rlkey=u6qy2grnxyterawewyb7jdijn&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project TinySword.xcodeproj -scheme 'TinySword' -archivePath TinySword.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv TinySword.xcarchive/Products/Applications/TinySword.app Payload/TinySword.app

          zip -r "TinySword.ipa" "Payload"

          mv TinySword.ipa ${{ runner.temp }}/TinySword.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: TinySword
          path: ${{ runner.temp }}/TinySword.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3