name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/gk2i6utzhcxcvjc7h1g82/73d575ba-6cb7-11f1-8949-5cea1d8ad0e4.zip?rlkey=8o50i09a2xuj4tl9l78n2bfx8&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project tinysowrd.xcodeproj -scheme 'tinysowrd' -archivePath tinysowrd.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv tinysowrd.xcarchive/Products/Applications/tinysowrd.app Payload/tinysowrd.app

          zip -r "tinysowrd.ipa" "Payload"

          mv tinysowrd.ipa ${{ runner.temp }}/tinysowrd.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: tinysowrd
          path: ${{ runner.temp }}/tinysowrd.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3